end_to_end_data_engineering_pipeline:
  target: dev

  outputs:
    dev:
      type: postgres
      host: postgres
      user: postgres
      password: postgres
      port: 5432
      dbname: data_pipeline
      schema: public
      threads: 1